# Generated by Django 3.2.15 on 2023-03-02 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device_management_app', '0004_remove_device_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='model',
            field=models.CharField(max_length=20),
        ),
    ]
