# Generated by Django 3.2.15 on 2023-03-02 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device_management_app', '0006_alter_device_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='status',
            field=models.CharField(default='not assigned', max_length=20),
        ),
        migrations.AlterField(
            model_name='device',
            name='model',
            field=models.CharField(max_length=50),
        ),
    ]
